# Generated by Django 5.1.4 on 2025-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='can_assign_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_delete_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_edit_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_modify_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_modify_roles',
            field=models.BooleanField(default=False),
        ),
    ]
