# Generated by Django 5.1.4 on 2025-07-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0002_usuario_can_assign_roles_usuario_can_delete_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_edit_accounts', models.BooleanField(default=False)),
                ('can_modify_accounts', models.BooleanField(default=False)),
                ('can_delete_accounts', models.BooleanField(default=False)),
                ('can_assign_roles', models.BooleanField(default=False)),
                ('can_modify_roles', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='can_assign_roles',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='can_delete_accounts',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='can_edit_accounts',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='can_modify_accounts',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='can_modify_roles',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='IS.rol'),
        ),
    ]
