# Generated by Django 5.1.4 on 2025-07-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0003_rol_remove_usuario_can_assign_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='can_assign_roles',
            new_name='can_access_historical_data',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='can_delete_accounts',
            new_name='can_activate_actuators',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='can_edit_accounts',
            new_name='can_configure_system',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='can_modify_accounts',
            new_name='can_consult_device_history',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='can_modify_roles',
            new_name='can_define_protocols',
        ),
        migrations.AddField(
            model_name='rol',
            name='can_generate_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_monitor_realtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_receive_critical_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_receive_maintenance_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_verify_sensor_status',
            field=models.BooleanField(default=False),
        ),
    ]
